const esp_idf = @import("esp").idf;
const board_build_config = @import("board_build_config");

pub const chip = board_build_config.chip;

pub const partition_table = esp_idf.PartitionTable.make(.{
    .entries = &.{
        .{
            .name = "nvs",
            .kind = .data,
            .subtype = .nvs,
            .size = 0x6000,
            .data = esp_idf.PartitionTable.data.nvs(.{}),
        },
        .{
            .name = "phy_init",
            .kind = .data,
            .subtype = .phy,
            .size = 0x1000,
        },
        .{
            .name = "coredump",
            .kind = .data,
            .subtype = .{ .custom_name = "coredump" },
            .size = 0x10000,
        },
        .{
            .name = "factory",
            .kind = .app,
            .subtype = .factory,
            .size = 0x600000,
        },
    },
});

pub const sdk_config = esp_idf.SdkConfig.make(.{
    .ESPTOOLPY_FLASHSIZE = "16MB",
    .ESPTOOLPY_FLASHSIZE_16MB = true,
    .ESPTOOLPY_FLASHSIZE_2MB = false,
    .ESP_WIFI_ENABLED = true,
    .ESP_WIFI_NVS_ENABLED = true,
    .ESP_WIFI_SLP_IRAM_OPT = true,
    .ESP_WIFI_STATIC_RX_BUFFER_NUM = 16,
    .ESP_WIFI_DYNAMIC_RX_BUFFER_NUM = 64,
    .ESP_WIFI_STATIC_TX_BUFFER = true,
    .ESP_WIFI_DYNAMIC_TX_BUFFER = false,
    .ESP_WIFI_TX_BUFFER_TYPE = 0,
    .ESP_WIFI_STATIC_TX_BUFFER_NUM = 24,
    .ESP_WIFI_CACHE_TX_BUFFER_NUM = 32,
    .ESP_WIFI_AMPDU_TX_ENABLED = true,
    .ESP_WIFI_TX_BA_WIN = 32,
    .ESP_WIFI_AMPDU_RX_ENABLED = true,
    .ESP_WIFI_RX_BA_WIN = 10,
    .ESP_WIFI_TASK_PINNED_TO_CORE_0 = true,
    .ESP_WIFI_TASK_PINNED_TO_CORE_1 = false,
    .ESP_MAIN_TASK_STACK_SIZE = 48 * 1024,
    .COMPILER_OPTIMIZATION_DEBUG = false,
    .COMPILER_OPTIMIZATION_SIZE = false,
    .COMPILER_OPTIMIZATION_PERF = true,
    .COMPILER_OPTIMIZATION_NONE = false,
    .ESP_TASK_WDT_EN = false,
    .ESP_TASK_WDT_INIT = false,
    .ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0 = false,
    .ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1 = false,
    .ESP_INT_WDT_TIMEOUT_MS = 3000,
    .ESP_COREDUMP_ENABLE_TO_FLASH = true,
    .ESP_COREDUMP_ENABLE_TO_UART = false,
    .ESP_COREDUMP_ENABLE_TO_NONE = false,
    .ESP_COREDUMP_CHECK_BOOT = true,
    .ESP_COREDUMP_MAX_TASKS_NUM = 16,
    .ESP_COREDUMP_STACK_SIZE = 2048,
    .ESP_DEFAULT_CPU_FREQ_MHZ_160 = false,
    .ESP_DEFAULT_CPU_FREQ_MHZ_240 = true,
    .ESP_DEFAULT_CPU_FREQ_MHZ = 240,
    .FREERTOS_HZ = 1000,
    .FREERTOS_USE_TRACE_FACILITY = true,
    .FREERTOS_GENERATE_RUN_TIME_STATS = true,
    .FREERTOS_RUN_TIME_STATS_USING_ESP_TIMER = true,
    .FREERTOS_RUN_TIME_STATS_USING_CPU_CLK = false,
    .LWIP_IRAM_OPTIMIZATION = true,
    .LWIP_TCPIP_TASK_PRIO = 23,
    .LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY = true,
    .LWIP_TCPIP_TASK_AFFINITY_CPU0 = false,
    .LWIP_TCPIP_TASK_AFFINITY_CPU1 = false,
    .LWIP_TCPIP_TASK_AFFINITY = esp_idf.SdkConfig.raw("0x7FFFFFFF"),
    .LWIP_TCPIP_RECVMBOX_SIZE = 64,
    .LWIP_TCP_RECVMBOX_SIZE = 64,
    .LWIP_UDP_RECVMBOX_SIZE = 64,
    .LWIP_SO_RCVBUF = true,
    .LWIP_TCP_SND_BUF_DEFAULT = 65535,
    .LWIP_TCP_WND_DEFAULT = 65535,
    .MBEDTLS_COMPILER_OPTIMIZATION_SIZE = false,
    .MBEDTLS_COMPILER_OPTIMIZATION_PERF = true,
    .MBEDTLS_COMPILER_OPTIMIZATION_NONE = false,
    .MBEDTLS_SSL_PROTO_TLS1_3 = true,
    .MBEDTLS_CHACHA20_C = true,
    .MBEDTLS_CHACHAPOLY_C = true,
    .SPIFFS_MAX_PARTITIONS = 3,
    .SPIRAM = true,
    .SPIRAM_MODE_QUAD = false,
    .SPIRAM_MODE_OCT = true,
    .SPIRAM_SPEED_40M = false,
    .SPIRAM_SPEED_80M = true,
    .SPIRAM_USE_CAPS_ALLOC = false,
    .SPIRAM_USE_MALLOC = true,
    .SPIRAM_MALLOC_ALWAYSINTERNAL = 0,
    .SPIRAM_TRY_ALLOCATE_WIFI_LWIP = true,
});
